### ISSUE TITLE
Ability to log

### ISSUE THREAD

**Issue by ctapobep** [sstephenson/bats#67]
I'd like to be able to log stuff (e.g. the $output, $status) in order to get a grip on what causes the test to fail.

**Comment by brikis98** [comment]
Is there a way to see log output when tests don't fail? For example, I have some tests that run slowly and I'd like to be able to output some sort of visual indication to stdout that something is actually happening...

**Comment by ztombol** [comment]
@brikis98 This issue was opened to _"display details once a test fails"_, which has been answered and since became easier with the [`bats-*` libraries](https://github.com/ztombol/bats-docs).

You are asking a different, but not less important, question that would have, in itself, worth opening a separate issue. Others may have a better answer, so consider opening a separate issue for visibility.

To answer your question. No, Bats only produces output once a test has exited, successfully or otherwise. See a possible workaround below.

### Workaround

To display information while a test is executing, for example to monitor a long running test, one can write to a log file and `tail -f` it.

``` bash
#!/usr/bin/env bats

log() {
  local -r log="log-${BATS_TEST_FILENAME##*/}"
  echo "$@" >> "$log"
}

@test 'long running test' {
  log "Starting test #${BATS_TEST_NUMBER}"

  # step 1
  log '  Step 1: Starting...'
  sleep 5
  log '  Step 1: Finished!'

  # step 2
  log '  Step 2: Starting...'
  sleep 5
  log '  Step 2: Finished!'

  log "Finished test #${BATS_TEST_NUMBER}"
}
```

Start the test as usual.

``` bash
$ bats test.bats
```

Then, in another terminal, `tail` the log file.

``` bash
$ tail -f -log-test.bats
```

And you can see how your tests are progressesing.

```
Starting test #1
  Step 1: Starting...
  Step 1: Finished!
  Step 2: Starting...
  Step 2: Finished!
Finished test #1
```

_**Note:** Removed non-[POSIX `tail`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/tail.html) options (`--retry`, `--follow` and `-F`). -- 2016-05-10 18:31 UTC_

**Comment by brikis98** [comment]
@ztombol The issue simply says "ability to log"; the "on failure" aspect was added only as part of the response. 

At any rate, thanks for the workaround. I've been doing basically that already, but having to manage and tail extra files is a bit tedious. It would be great to have a flag like `--verbose` or `--debug` that shows stdout/stderr in the terminal during test execution. If it helps to have a separate issue for that, I'm happy to open one.

**Comment by ztombol** [comment]
Yeah, I know the workaround is tedious. This feature would be useful. If I'm correct, this is similar what have been asked in (#96) and proposed in (#149). If you think your suggestion is different, I think it worth opening a new issue.

I'm currently going over the issue tracker looking for features and issues that could be addressed in the next release (being organised in #150). This would be a useful feature, so I'm adding it to the list!

**Comment by brikis98** [comment]
Ah, #149 would be perfect! I'm very happy to hear it's on the list of possibilities for the next release. Thanks!
