### ISSUE TITLE
Publish this package on npm?

### ISSUE THREAD

**Issue by wcandillon** [sstephenson/bats#95]
Right now, I have to use the github URL.

**Comment by orlin** [comment]
@wcandillon I needed the same thing and published `bats` as [batshit](https://github.com/orlin/batshit).  Chose a different name out of respect for bats, and this particular one for some humor + due to a funny story about bats shit I heard last summer, and most importantly to avoid ambiguity about which bats is running if bats is manually installed -- batshit auto-installs itself globally...

@sstephenson I had it tied to the latest tag and will try to keep-up with releases.  Though I could also disappear just when someone needs the latest version.  It depends on a couple of other modules I wrote to scratch some itches.  Let me know what you think of this and also if you want to npm-publish batshit yourself.  We could call it bats too.

**Comment by clux** [comment]
This would be great. Batshit already works ok, but it is still cloning from github. Would be a lot easier for people with strict ACLs on build networks if stuff could flow through package managers.

**Comment by thomasjo** [comment]
Uhmm... why should this be published on npm, a package manager for Node.js? Just because you can, doesn't mean you should. And this is one of those times when you should *not*. Let's not pollute npm any further.

**Comment by sstephenson** [comment]
I don’t understand why Bats should be published to a JavaScript package repository.

Are you confused by the presence of [package.json](https://github.com/sstephenson/bats/blob/master/package.json)? That’s there to support [bpkg](https://github.com/sstephenson/bats/pull/60).

**Comment by clux** [comment]
Oh whoops. Those are very similar conventions - I just assumed publishing on npm was an eventual goal.  Which would be convenient, but probably a little weird. More so if it already exists elsewhere. Please ignore my request.

**Comment by sstephenson** [comment]
Ok, cool. Thought maybe there was some other use case I was missing.
